import type { Callout } from "./callouts-mirage";

// Anubis — egyptian temple map, 2023 addition.
// Heavy mid focus, water canals, palm trees, bridge.
export const ANUBIS_CALLOUTS: Callout[] = [
  { id: "t_spawn",    en: "T Spawn",       ru: "Т-спавн",      es: "T Spawn",       poly: "40,40 220,40 220,160 40,160",
    desc_en: "Terrorist starting area. Three paths: A via Ramp, Mid via Alley, B via Canal.",
    desc_ru: "Т-спавн. Три пути: на А через рампу, в мид через аллею, на Б через канал.",
    desc_es: "Spawn T. Tres rutas: A por Ramp, Mid por Alley, B por Canal." },
  { id: "t_ramp",     en: "T Ramp",        ru: "Т-рамп",       es: "Ramp T",        poly: "240,40 400,40 400,120 240,120",
    desc_en: "Ramp up from T toward A Site. First smoke cover of any A execute.",
    desc_ru: "Рампа от Т к А-пленту. Первое прикрытие смоуком любого А-захода.",
    desc_es: "Rampa desde T hacia A. Primera cobertura de humo en todo execute A." },
  { id: "a_main",     en: "A Main",        ru: "А-мэйн",       es: "A Main",        poly: "420,40 600,40 600,160 420,160",
    desc_en: "Main entry to A. Two chokes: Palace and Default.",
    desc_ru: "Главный вход на А. Два чока: Палас и Дефолт.",
    desc_es: "Entrada principal al A. Dos chokes: Palace y Default." },
  { id: "palace",     en: "Palace",        ru: "Палас",        es: "Palace",        poly: "620,40 760,40 760,160 620,160",
    desc_en: "Elevated structure on A. CT AWPers live here — anchor or die.",
    desc_ru: "Приподнятая конструкция на А. Тут живут СТ-AWP'еры — якорь или смерть.",
    desc_es: "Estructura elevada en A. Acá viven los AWPers CT — anchor o morís." },
  { id: "a_site",     en: "A Site",        ru: "А-плент",      es: "Sitio A",       poly: "440,180 760,180 760,320 440,320",
    desc_en: "Bombsite A. Palm tree cover, palace overlook, water on the side.",
    desc_ru: "А-плент. Пальмовое прикрытие, обзор с Паласа, вода сбоку.",
    desc_es: "Sitio A. Cobertura de palmeras, overlook desde Palace, agua al costado." },
  { id: "palm",       en: "Palm",          ru: "Пальма",       es: "Palmera",       poly: "480,220 560,220 560,280 480,280",
    desc_en: "Palm tree on A — classic default plant hiding spot.",
    desc_ru: "Пальма на А — классическое место для дефолт-постановки.",
    desc_es: "Palmera en A — escondite clásico para el plant default." },
  { id: "heaven_a",   en: "Heaven",        ru: "Хэвен",        es: "Heaven",        poly: "660,180 760,180 760,260 660,260",
    desc_en: "High ground overlooking A site from CT side. Impossible angle.",
    desc_ru: "Верхняя точка над А-плентом со стороны СТ. Нереальный угол.",
    desc_es: "Terreno alto sobre A desde lado CT. Ángulo imposible." },
  { id: "alley",      en: "Alley",         ru: "Аллея",        es: "Callejón",      poly: "240,160 400,160 400,280 240,280",
    desc_en: "T-side alley connecting T Spawn to Mid. Narrow, smoke-heavy.",
    desc_ru: "Т-аллея от спавна в мид. Узкая, много смоуков.",
    desc_es: "Callejón T de Spawn a Mid. Angosta, muchos humos." },
  { id: "mid",        en: "Mid",           ru: "Мид",          es: "Mid",           poly: "260,300 420,300 420,500 260,500",
    desc_en: "Central open area with bridge and water. Lost Mid = lost round.",
    desc_ru: "Центральная открытая зона с мостом и водой. Потерял мид — потерял раунд.",
    desc_es: "Zona central abierta con puente y agua. Mid perdido = ronda perdida." },
  { id: "bridge",     en: "Bridge",        ru: "Мост",         es: "Puente",        poly: "300,340 400,340 400,400 300,400",
    desc_en: "The iconic stone bridge crossing Mid. Jump spot with headshot angles.",
    desc_ru: "Знаменитый каменный мост через мид. Прыжок с хедшот-углами.",
    desc_es: "El icónico puente de piedra cruzando Mid. Salto con ángulos de headshot." },
  { id: "water",      en: "Water",         ru: "Вода",         es: "Agua",          poly: "260,500 420,500 420,560 260,560",
    desc_en: "The water canal under the bridge. Slow movement — loud splashes.",
    desc_ru: "Водный канал под мостом. Медленное движение — громкие плески.",
    desc_es: "El canal de agua bajo el puente. Movimiento lento — salpicaduras ruidosas." },
  { id: "connector_a", en: "A Connector",  ru: "А-коннектор",  es: "Conector A",    poly: "440,340 560,340 560,440 440,440",
    desc_en: "Mid-to-A connector. CTs rotate here after losing Mid.",
    desc_ru: "Коннектор из мида на А. СТ ротируется сюда после проигрыша мида.",
    desc_es: "Conector Mid-A. CTs rotan acá tras perder Mid." },
  { id: "connector_b", en: "B Connector",  ru: "Б-коннектор",  es: "Conector B",    poly: "440,460 560,460 560,560 440,560",
    desc_en: "Mid-to-B connector. Fast rotation path.",
    desc_ru: "Коннектор из мида на Б. Быстрая ротация.",
    desc_es: "Conector Mid-B. Ruta de rotación rápida." },
  { id: "b_canal",    en: "B Canal",       ru: "Б-канал",      es: "Canal B",       poly: "40,460 220,460 220,580 40,580",
    desc_en: "T entry to B through the water canal. Ninja approach.",
    desc_ru: "Т-заход на Б через водный канал. Ниндзя-подход.",
    desc_es: "Entrada T al B por el canal. Aproximación ninja." },
  { id: "b_site",     en: "B Site",        ru: "Б-плент",      es: "Sitio B",       poly: "40,600 340,600 340,780 40,780",
    desc_en: "Bombsite B. Tight, covered. Plant behind Truck or Boxes.",
    desc_ru: "Б-плент. Тесный, закрытый. Ставят за грузовиком или ящиками.",
    desc_es: "Sitio B. Cerrado, cubierto. Plant detrás del Truck o Cajas." },
  { id: "truck",      en: "Truck",         ru: "Грузовик",     es: "Camión",        poly: "60,640 160,640 160,720 60,720",
    desc_en: "Truck on B — the main plant cover. Smoke it from CT side.",
    desc_ru: "Грузовик на Б — главное прикрытие постановки. Дымится с СТ.",
    desc_es: "Camión en B — cobertura principal del plant. Se humea desde CT." },
  { id: "boxes_b",    en: "Boxes",         ru: "Ящики",        es: "Cajas",         poly: "180,640 280,640 280,720 180,720",
    desc_en: "Stacked boxes on B — secondary plant spot.",
    desc_ru: "Ящики на Б — вторичная постановка.",
    desc_es: "Cajas apiladas en B — plant secundario." },
  { id: "pharmacy",   en: "Pharmacy",      ru: "Фармация",     es: "Farmacia",      poly: "360,600 500,600 500,720 360,720",
    desc_en: "LATAM-known as 'Farmacia'. CT room near B — rotating defender hides here.",
    desc_ru: "В LATAM известно как 'Фармация'. СТ-комната у Б — сюда прячется защитник.",
    desc_es: "Conocida en LATAM como 'Farmacia'. Sala CT cerca de B — acá se esconde el defensor." },
  { id: "heaven_b",   en: "B Heaven",      ru: "Б-хэвен",      es: "B Heaven",      poly: "360,740 480,740 480,780 360,780",
    desc_en: "High CT angle onto B Site. Rotate here post-execute to clear Boxes.",
    desc_ru: "Верхний СТ-угол на Б. Ротироваться сюда после захода — чистить ящики.",
    desc_es: "Ángulo CT alto sobre B. Rotar acá post-execute para limpiar las cajas." },
  { id: "ct_spawn",   en: "CT Spawn",      ru: "СТ-спавн",     es: "Spawn CT",      poly: "620,560 760,560 760,760 620,760",
    desc_en: "CT starting position. 7 seconds to A, 9 to B. Mid is fastest.",
    desc_ru: "СТ-спавн. 7 секунд до А, 9 до Б. Мид быстрее всего.",
    desc_es: "Spawn CT. 7 seg al A, 9 al B. Mid es el más rápido." },
  { id: "ct_mid",     en: "CT Mid",        ru: "СТ-мид",       es: "CT Mid",        poly: "580,300 660,300 660,440 580,440",
    desc_en: "CT side of Mid. Where the round-1 AWP duel happens.",
    desc_ru: "СТ-сторона мида. Там где происходит AWP-дуэль первого раунда.",
    desc_es: "Lado CT de Mid. Donde pasa el duelo de AWP ronda 1." },
];
