import type { Callout } from "./callouts-mirage";

// Inferno callouts — schematic layout on 800x800 viewBox.
// Italian village: narrow alleys, apartments, arches, pit.
export const INFERNO_CALLOUTS: Callout[] = [
  { id: "t_spawn",   en: "T Spawn",       ru: "Т-спавн",      es: "T Spawn",       poly: "40,40 240,40 240,160 40,160",
    desc_en: "Terrorist spawn, top-left of map. Mid takes ~11 seconds from here.",
    desc_ru: "Т-спавн, верх-лево карты. До мида отсюда ~11 секунд.",
    desc_es: "Spawn T, arriba a la izquierda. Al mid son ~11 segundos." },
  { id: "mid",       en: "Mid",           ru: "Мид",          es: "Mid",           poly: "260,60 400,60 400,280 260,280",
    desc_en: "The narrow central corridor with the fountain. T-side loses 2v2 here most rounds.",
    desc_ru: "Узкий центральный коридор с фонтаном. Т-сторона чаще сливает 2v2 здесь.",
    desc_es: "Corredor central angosto con la fuente. El lado T pierde 2v2 seguido." },
  { id: "second_mid", en: "Second Mid",    ru: "Второй мид",   es: "Second Mid",    poly: "260,300 400,300 400,380 260,380",
    desc_en: "Short alley past the fountain — leads toward B Short / Apartments.",
    desc_ru: "Короткий проход за фонтаном — ведёт к шорту/апартаментам Б.",
    desc_es: "Callejón corto pasando la fuente — lleva a Short B / Apartamentos." },
  { id: "apps",      en: "Apps",          ru: "Апартаменты",  es: "Apartamentos",  poly: "60,200 240,200 240,380 60,380",
    desc_en: "Apartments. Two floors, critical T-rotation path to B and pixel angles.",
    desc_ru: "Апартаменты. Два этажа, ключевая Т-ротация на Б и пиксель-углы.",
    desc_es: "Apartamentos. Dos pisos, rotación clave T hacia B y pixel angles." },
  { id: "balcony",   en: "Balcony",        ru: "Балкон",       es: "Balcón",        poly: "60,380 170,380 170,460 60,460",
    desc_en: "Apps balcony overlooking B Site. Wicked pre-aim battleground.",
    desc_ru: "Балкон апсов над Б-плентом. Жёсткое место для преаима.",
    desc_es: "Balcón de Apps sobre el sitio B. Preaim brutal." },
  { id: "b_site",    en: "B Site",        ru: "Б-плент",      es: "Sitio B",       poly: "200,480 440,480 440,620 200,620",
    desc_en: "Bombsite B. Two entries: Banana (CT side) and Apps (T side).",
    desc_ru: "Б-плент. Два входа: Банан (СТ) и Апсы (Т).",
    desc_es: "Sitio B. Dos entradas: Banana (CT) y Apps (T)." },
  { id: "coffin",    en: "Coffin",        ru: "Гроб",         es: "Ataúd",         poly: "260,500 320,500 320,560 260,560",
    desc_en: "The long box on B where CTs hide post-plant. Common molly spot.",
    desc_ru: "Длинный ящик на Б, где СТ прячется после постановки. Классика для молли.",
    desc_es: "La caja larga en B donde los CT se esconden post-plant. Classic molly." },
  { id: "new_box",   en: "New Box",       ru: "Новый бокс",   es: "Caja nueva",    poly: "340,500 400,500 400,560 340,560",
    desc_en: "Plant spot behind the newer box on B. Safe from Arch and Banana.",
    desc_ru: "Постановка за новым боксом на Б. Безопасно от Арки и Банана.",
    desc_es: "Plantar detrás de la caja nueva en B. Seguro de Arch y Banana." },
  { id: "sand",      en: "Sandbags",      ru: "Мешки",        es: "Sandbags",      poly: "460,550 560,550 560,620 460,620",
    desc_en: "Sandbag wall between B and CT. Critical AWP angle toward Banana.",
    desc_ru: "Стена из мешков между Б и СТ. Ключевой AWP-угол на Банан.",
    desc_es: "Muro de sandbags entre B y CT. Ángulo clave de AWP hacia Banana." },
  { id: "dark",      en: "Dark",          ru: "Дарк",         es: "Dark",          poly: "200,620 320,620 320,700 200,700",
    desc_en: "Dark corner on B. Pure ninja-defuse territory.",
    desc_ru: "Тёмный угол на Б. Территория ниндзя-дефьюза.",
    desc_es: "Rincón oscuro en B. Territorio puro de ninja defuse." },
  { id: "banana",    en: "Banana",        ru: "Банан",        es: "Banana",        poly: "460,260 600,260 600,540 480,540",
    desc_en: "The infamous curved choke to B. First smoke contest every round.",
    desc_ru: "Легендарный изогнутый чок на Б. Первый смоук-батл каждый раунд.",
    desc_es: "El famoso choke curvo hacia B. Batalla de humos cada primera ronda." },
  { id: "car",       en: "Car",           ru: "Машина",       es: "Auto",          poly: "480,440 560,440 560,520 480,520",
    desc_en: "The red car in Banana. Common T-smoke position against CT Banana.",
    desc_ru: "Красная машина на Банане. Частая позиция для Т-смоука против СТ на Банане.",
    desc_es: "El auto rojo en Banana. Posición común T para smoke contra CT." },
  { id: "logs",      en: "Logs",          ru: "Брёвна",       es: "Troncos",       poly: "480,280 560,280 560,380 480,380",
    desc_en: "Stacked logs in Banana. CT-side pre-aim spot for Banana control.",
    desc_ru: "Брёвна на Банане. СТ-позиция для преаима контроля Банана.",
    desc_es: "Troncos apilados en Banana. Posición CT para preaim de Banana." },
  { id: "ct_spawn",  en: "CT Spawn",      ru: "СТ-спавн",     es: "Spawn CT",      poly: "620,560 780,560 780,760 620,760",
    desc_en: "CT starting position. 10 seconds to Banana, 8 seconds to Arch.",
    desc_ru: "СТ-спавн. 10 секунд до Банана, 8 секунд до Арки.",
    desc_es: "Spawn CT. 10 seg a Banana, 8 seg al Arch." },
  { id: "arch",      en: "Arch",          ru: "Арка",         es: "Arch",          poly: "460,40 620,40 620,240 460,240",
    desc_en: "The arch leading to A Site from Mid. Iconic post-plant view from Ruins.",
    desc_ru: "Арка, ведущая на А-плент из мида. Культовый пост-плант вид из Руин.",
    desc_es: "El arco hacia el sitio A desde Mid. Vista icónica post-plant desde Ruins." },
  { id: "short",     en: "Short",         ru: "Шорт",         es: "Short",         poly: "400,60 460,60 460,240 400,240",
    desc_en: "Short A. Thin gap connecting Mid to A Site — fast rotation lane.",
    desc_ru: "Шорт А. Узкий проход, соединяющий мид и А — быстрая ротация.",
    desc_es: "Short A. Pasillo angosto conectando Mid al A — ruta rápida." },
  { id: "a_site",    en: "A Site",        ru: "А-плент",      es: "Sitio A",       poly: "640,40 780,40 780,300 640,300",
    desc_en: "Bombsite A. Three entry angles: Arch, Short, and Apps.",
    desc_ru: "А-плент. Три угла захода: Арка, Шорт и Апсы.",
    desc_es: "Sitio A. Tres ángulos de entrada: Arch, Short y Apps." },
  { id: "pit",       en: "Pit",           ru: "Пит",          es: "Pit",           poly: "660,260 750,260 750,360 660,360",
    desc_en: "Sunken area on A. Classic CT anchor position — high ground for defense.",
    desc_ru: "Углублённая зона на А. Классический якорь СТ — высота для защиты.",
    desc_es: "Zona hundida en A. Anchor CT clásico — terreno alto para defensa." },
  { id: "graveyard", en: "Graveyard",     ru: "Кладбище",     es: "Cementerio",    poly: "640,300 780,300 780,440 640,440",
    desc_en: "Back corner of A near CT. Where post-plant defenders hide.",
    desc_ru: "Дальний угол А у СТ. Здесь прячется постпланта защита.",
    desc_es: "Rincón trasero de A cerca de CT. Ahí se esconden post-plant." },
  { id: "library",   en: "Library",       ru: "Библиотека",   es: "Biblioteca",    poly: "540,40 640,40 640,180 540,180",
    desc_en: "Library on the way to A. Often smoked off during A executes.",
    desc_ru: "Библиотека по пути на А. Часто дымится при А-исполнениях.",
    desc_es: "Biblioteca en el camino al A. Se humea seguido durante executes A." },
  { id: "boiler",    en: "Boiler",        ru: "Бойлер",       es: "Boiler",        poly: "260,400 380,400 380,460 260,460",
    desc_en: "Off-angle room between Apps and B. Sneaky wrap position.",
    desc_ru: "Off-angle комната между Апсами и Б. Коварная позиция для обхода.",
    desc_es: "Sala off-angle entre Apps y B. Posición wrap sneaky." },
  { id: "ruins",     en: "Ruins",         ru: "Руины",        es: "Ruinas",        poly: "420,240 500,240 500,320 420,320",
    desc_en: "Stone ruins in Mid, the forward T-aggression spot.",
    desc_ru: "Каменные руины в миде, точка форвард-агрессии Т.",
    desc_es: "Ruinas de piedra en Mid, punto de agresión forward T." },
  { id: "top_banana", en: "Top Banana",    ru: "Топ банан",    es: "Top Banana",    poly: "540,260 600,260 600,340 540,340",
    desc_en: "The elevated start of Banana from CT side — contest point round 1.",
    desc_ru: "Верх Банана с СТ стороны — спорная точка первого раунда.",
    desc_es: "El inicio elevado de Banana del lado CT — punto disputado ronda 1." },
  { id: "pope",      en: "Pope",          ru: "Папа",         es: "Papa",          poly: "540,360 620,360 620,440 540,440",
    desc_en: "Small T-side jumpable spot near Banana. Peek-prediction gold.",
    desc_ru: "Небольшая Т-позиция прыжком у Банана. Золото для peek-prediction.",
    desc_es: "Posición T saltable cerca de Banana. Oro para peek-prediction." },
];
