import type { Callout } from "./callouts-mirage";

// Nuke — the vertical map. Two floors, outside, ramp, vents.
// We show both levels stacked: Upper 0..400, Lower 400..800.
// viewBox 800x800. Horizontal line at y=400 divides the floors.
export const NUKE_CALLOUTS: Callout[] = [
  // ═══ UPPER LEVEL (A Site + rooms around it) ═══
  { id: "outside",       en: "Outside",         ru: "Аутсайд",     es: "Outside",       poly: "40,40 300,40 300,200 40,200",
    desc_en: "The huge open yard T uses to access the map. Contested early round.",
    desc_ru: "Большой открытый двор, откуда Т заходит. Оспаривается с первой секунды.",
    desc_es: "El enorme patio abierto por donde entra el T. Disputado desde el principio." },
  { id: "silo",          en: "Silo",            ru: "Силос",       es: "Silo",          poly: "60,220 180,220 180,340 60,340",
    desc_en: "Tall cylinder outside. T-side AWP angle into Outside.",
    desc_ru: "Высокий цилиндр на аутсайде. Т-AWP угол на Аутсайд.",
    desc_es: "Cilindro alto en Outside. Ángulo de AWP T hacia Outside." },
  { id: "garage",        en: "Garage",          ru: "Гараж",       es: "Garage",        poly: "200,220 320,220 320,340 200,340",
    desc_en: "The garage doorway leading to Outside. Classic smoke target.",
    desc_ru: "Ворота гаража, ведущие на Аутсайд. Классическая цель для смоука.",
    desc_es: "La puerta del garage hacia Outside. Objetivo clásico de humo." },
  { id: "heaven",        en: "Heaven",          ru: "Хэвен",       es: "Heaven",        poly: "440,40 560,40 560,140 440,140",
    desc_en: "High ground on A overlooking the site. AWP paradise — anchor here.",
    desc_ru: "Верхняя точка над А-плентом. Рай для AWP — якорь.",
    desc_es: "Terreno alto en A. Paraíso de AWP — anchor acá." },
  { id: "a_site_u",      en: "A Site",          ru: "А-плент",     es: "Sitio A",       poly: "440,160 720,160 720,320 440,320",
    desc_en: "Upper bombsite. Vents under, Heaven above, Hut on the side. Brutal to retake.",
    desc_ru: "Верхний плент. Вентиляция снизу, Хэвен сверху, Хат сбоку. Жестоко для ретейка.",
    desc_es: "Sitio superior. Vents abajo, Heaven arriba, Hut al costado. Terrible para retake." },
  { id: "hut",           en: "Hut",             ru: "Хат",         es: "Hut",           poly: "600,40 720,40 720,140 600,140",
    desc_en: "Small shed on A near Heaven. Off-angle CT hide.",
    desc_ru: "Небольшая будка на А возле Хэвена. Off-angle для СТ.",
    desc_es: "Cabaña chica en A cerca de Heaven. Off-angle CT." },
  { id: "rafters",       en: "Rafters",         ru: "Рафтеры",     es: "Rafters",       poly: "340,40 440,40 440,160 340,160",
    desc_en: "Elevated beams above A. Risky push perch with wallbang potential.",
    desc_ru: "Приподнятые балки над А. Рискованная позиция пуша, пробиваемо.",
    desc_es: "Vigas elevadas sobre A. Posición arriesgada, wallbangeable." },
  { id: "squeaky",       en: "Squeaky",         ru: "Скрипучка",   es: "Squeaky",       poly: "340,180 440,180 440,280 340,280",
    desc_en: "The squeaky door to A from Outside. Everyone hears it. Everyone.",
    desc_ru: "Скрипучая дверь на А с Аутсайда. Её слышит каждый. Каждый.",
    desc_es: "La puerta chirriante al A desde Outside. La escuchan todos." },
  { id: "mini",          en: "Mini",            ru: "Мини",        es: "Mini",          poly: "460,340 560,340 560,400 460,400",
    desc_en: "Small object on A — classic default plant behind it.",
    desc_ru: "Мелкий ящик на А — дефолтная постановка за ним.",
    desc_es: "Objeto chico en A — plant default detrás." },
  { id: "a_default",     en: "Default",         ru: "Дефолт",      es: "Default",       poly: "580,340 680,340 680,400 580,400",
    desc_en: "Standard plant spot on A — contested from Heaven and CT.",
    desc_ru: "Стандартная постановка на А — оспаривается с Хэвена и СТ.",
    desc_es: "Plant estándar en A — disputado desde Heaven y CT." },
  { id: "t_ramp",        en: "T Ramp",          ru: "Т-рамп",      es: "Ramp T",        poly: "60,360 220,360 220,400 60,400",
    desc_en: "T ramp leading up from Outside. Bridge to Main execute.",
    desc_ru: "Т-рампа, ведущая наверх с аутсайда. Мост к исполнению Main.",
    desc_es: "Rampa T subiendo desde Outside. Puente al execute Main." },

  // ═══ LOWER LEVEL (B Site + Ramp) ═══
  { id: "lobby",         en: "Lobby",           ru: "Лобби",       es: "Lobby",         poly: "40,440 220,440 220,540 40,540",
    desc_en: "T entry corridor to lower level. The first smoke target.",
    desc_ru: "Т-коридор на нижний этаж. Первая цель смоука.",
    desc_es: "Pasillo T al nivel inferior. Primer objetivo de humo." },
  { id: "ramp",          en: "Ramp",            ru: "Рамп",        es: "Ramp",          poly: "240,440 380,440 380,580 240,580",
    desc_en: "The ramp down to B. Contested every B-execute.",
    desc_ru: "Рампа вниз к Б. Борьба за неё при каждом заходе на Б.",
    desc_es: "Rampa bajando a B. Disputada en cada execute B." },
  { id: "secret",        en: "Secret",          ru: "Сикрет",      es: "Secret",        poly: "60,560 200,560 200,640 60,640",
    desc_en: "Flank route from Outside into lower. Classic wrap-around for B-support.",
    desc_ru: "Фланг-маршрут с Аутсайда на нижний. Классический обход для Б-саппорта.",
    desc_es: "Ruta de flanqueo desde Outside al nivel inferior. Wrap-around clásico B-support." },
  { id: "b_site",        en: "B Site",          ru: "Б-плент",     es: "Sitio B",       poly: "240,600 500,600 500,780 240,780",
    desc_en: "Lower bombsite. Entries: Ramp, Lobby, and Vents from above.",
    desc_ru: "Нижний плент. Заходы: Рамп, Лобби и Вентиляция сверху.",
    desc_es: "Sitio inferior. Entradas: Rampa, Lobby y Vents de arriba." },
  { id: "dog",           en: "Dog",             ru: "Дог",         es: "Dog",           poly: "260,640 340,640 340,720 260,720",
    desc_en: "Small crate on B named after the old Sven Co-op dog. Plant behind it.",
    desc_ru: "Ящик на Б, названный в честь пса из Sven Co-op. Постановка за ним.",
    desc_es: "Caja en B, nombrada por el perro del Sven Co-op. Plant detrás." },
  { id: "control_room",  en: "Control Room",    ru: "Контроль",    es: "Sala Control",  poly: "360,640 500,640 500,720 360,720",
    desc_en: "Back room on B — CTs rotate through here from Main/Secret.",
    desc_ru: "Задняя комната на Б — СТ ротируется сюда с Main/Сикрет.",
    desc_es: "Sala trasera de B — CTs rotan por acá desde Main/Secret." },
  { id: "vent_drop",     en: "Vent Drop",       ru: "Вент-дроп",   es: "Vent Drop",     poly: "380,440 500,440 500,580 380,580",
    desc_en: "Vent shaft connecting Upper and Lower. The notorious drop onto B.",
    desc_ru: "Шахта вентиляции, связывающая этажи. Легендарный дроп на Б.",
    desc_es: "Ducto que conecta pisos. El famoso drop al B." },
  { id: "big_door",      en: "Big Door",        ru: "Большая дверь",es: "Big Door",     poly: "520,440 640,440 640,540 520,540",
    desc_en: "Massive door between Main and B. Typically smoked by T during execute.",
    desc_ru: "Огромная дверь между Main и Б. Обычно дымится Т-стороной.",
    desc_es: "Enorme puerta entre Main y B. Típicamente humeada por T en execute." },
  { id: "main",          en: "Main",            ru: "Main",        es: "Main",          poly: "520,560 640,560 640,700 520,700",
    desc_en: "CT-side connector between A and B. Crucial rotation lane.",
    desc_ru: "СТ-коннектор между А и Б. Критический путь ротации.",
    desc_es: "Conector CT entre A y B. Ruta de rotación crucial." },

  // ═══ BOTH / CT SIDE ═══
  { id: "ct_spawn",      en: "CT Spawn",        ru: "СТ-спавн",    es: "Spawn CT",      poly: "660,440 780,440 780,700 660,700",
    desc_en: "CT start. Seconds to A: 4 · to B: 7. Fastest rotation in CS.",
    desc_ru: "СТ-старт. До А: 4 сек, до Б: 7. Самая быстрая ротация в CS.",
    desc_es: "Spawn CT. Al A: 4 seg · al B: 7. La rotación más rápida de CS." },
  { id: "t_spawn",       en: "T Spawn",         ru: "Т-спавн",     es: "T Spawn",       poly: "40,40 120,40 120,100 40,100",
    desc_en: "T start, top-left. Tight corner — your life begins here.",
    desc_ru: "Т-старт, верх-лево. Тесный угол — здесь начинается жизнь.",
    desc_es: "Spawn T, arriba a la izquierda. Rincón estrecho — tu vida arranca acá." },
  { id: "trophy",        en: "Trophy",          ru: "Трофей",      es: "Trophy",        poly: "220,120 320,120 320,180 220,180",
    desc_en: "The missile trophy display outside. Iconic off-angle.",
    desc_ru: "Стенд с ракетой-трофеем снаружи. Культовый off-angle.",
    desc_es: "Exhibición del misil trofeo afuera. Off-angle icónico." },
  { id: "radio",         en: "Radio",           ru: "Радио",       es: "Radio",         poly: "320,40 440,40 440,140 320,140",
    desc_en: "Radio tower room off Outside. Jump spot for elite peeks.",
    desc_ru: "Радиобашня у Аутсайда. Прыжок для элитных пиков.",
    desc_es: "Sala de la torre de radio. Salto para peeks elite." },
  { id: "window",        en: "Window",          ru: "Окно",        es: "Ventana",       poly: "720,180 780,180 780,320 720,320",
    desc_en: "Window on A near CT. Small opening, big headshot potential.",
    desc_ru: "Окно на А у СТ. Маленькое, но с большим headshot-потенциалом.",
    desc_es: "Ventana en A cerca de CT. Pequeña pero letal para headshots." },
];
