import type { Callout } from "./callouts-mirage";

// Dust 2 — the classic. Long A, Mid, Tunnels, B, two sites.
// viewBox 800x800. T spawn top-left, CT spawn bottom-right.
export const DUST2_CALLOUTS: Callout[] = [
  { id: "t_spawn",     en: "T Spawn",        ru: "Т-спавн",      es: "T Spawn",       poly: "40,40 240,40 240,160 40,160",
    desc_en: "Terrorist starting area. Path splits into Long, Mid, and Tunnels.",
    desc_ru: "Спавн террористов. Отсюда — Лонг, Мид или Туннели.",
    desc_es: "Spawn T. De acá sale Long, Mid o Túneles." },
  { id: "long_doors",  en: "Long Doors",     ru: "Длинные двери",es: "Puertas Long",  poly: "260,60 400,60 400,140 260,140",
    desc_en: "The garage doors that open Long A. First smoke of every Long execute.",
    desc_ru: "Ворота, открывающие Лонг-А. Первый смоук любого заходa на Лонг.",
    desc_es: "Las puertas que abren Long A. Primer humo de todo execute Long." },
  { id: "long",        en: "Long A",         ru: "Лонг",         es: "Long A",        poly: "420,60 640,60 640,180 420,180",
    desc_en: "The infamous long corridor to A Site. Classic AWP duel zone round one.",
    desc_ru: "Знаменитый длинный коридор на А. Классическая зона AWP-дуэлей первого раунда.",
    desc_es: "El famoso pasillo largo al A. Zona clásica de duelos de AWP ronda 1." },
  { id: "blue",        en: "Blue Car",       ru: "Синяя машина", es: "Auto Azul",     poly: "520,200 600,200 600,260 520,260",
    desc_en: "Small car on Long. Key T-side smoke cover after opening doors.",
    desc_ru: "Машина на Лонге. Ключевое прикрытие Т после открытия ворот.",
    desc_es: "Auto en Long. Cobertura T clave tras abrir las puertas." },
  { id: "pit",         en: "Pit",            ru: "Пит",          es: "Pit",           poly: "640,60 760,60 760,200 640,200",
    desc_en: "Sunken corner at end of Long. Classic CT AWP hold — pit peek or get lasered.",
    desc_ru: "Углубление в конце Лонга. Классика для СТ AWP — пикни или пулю в голову.",
    desc_es: "Rincón hundido al final de Long. Clásico anchor CT — peek o te comés un tiro." },
  { id: "a_site",      en: "A Site",         ru: "А-плент",      es: "Sitio A",       poly: "480,240 760,240 760,440 480,440",
    desc_en: "Bombsite A. Entries from Long, Catwalk/Short, and from CT Spawn.",
    desc_ru: "А-плент. Заходы с Лонга, Кэта и СТ-спавна.",
    desc_es: "Sitio A. Entradas desde Long, Cat y Spawn CT." },
  { id: "goose",       en: "Goose",          ru: "Гусь",         es: "Goose",         poly: "500,280 580,280 580,340 500,340",
    desc_en: "The small wall on A near Long. Default plant cover, smoke it off.",
    desc_ru: "Стенка на А у Лонга. Дефолтное прикрытие постановки, её дымят.",
    desc_es: "Muro chico en A cerca de Long. Cobertura default para plantar, se humea." },
  { id: "elevator",    en: "Elevator",       ru: "Элеватор",     es: "Elevador",      poly: "700,280 760,280 760,380 700,380",
    desc_en: "Raised platform on A. Ninja defuse angle and CT fallback.",
    desc_ru: "Поднятая платформа на А. Угол для ниндзя-дефьюза и отступа СТ.",
    desc_es: "Plataforma elevada en A. Ángulo de ninja defuse y fallback CT." },
  { id: "ct_cross",    en: "CT Cross",       ru: "СТ-кросс",     es: "CT Cross",      poly: "620,400 760,400 760,480 620,480",
    desc_en: "CT-side entry to A. First defender rotates here.",
    desc_ru: "СТ-заход на А. Первый защитник ротируется сюда.",
    desc_es: "Entrada CT al A. Primer defensor rota por acá." },
  { id: "short",       en: "Short A",        ru: "Шорт А",       es: "Short A",       poly: "380,280 480,280 480,420 380,420",
    desc_en: "Also called Catwalk. Short connector from Mid to A.",
    desc_ru: "Он же Кэт. Короткий коннектор из мида на А.",
    desc_es: "También Cat. Conector corto de Mid al A." },
  { id: "catwalk",     en: "Catwalk",        ru: "Кэт",          es: "Cat",           poly: "380,180 460,180 460,280 380,280",
    desc_en: "Upper Catwalk, leading to A from Mid. Jumping spot for speedy entries.",
    desc_ru: "Верхний Кэт, ведёт на А из мида. Прыжковая точка для быстрых заходов.",
    desc_es: "Cat superior, lleva al A desde Mid. Salto para entries rápidas." },
  { id: "mid_doors",   en: "Mid Doors",      ru: "Мид-двери",    es: "Puertas Mid",   poly: "260,160 380,160 380,240 260,240",
    desc_en: "Doors splitting T Mid. The first barrier when pushing Mid.",
    desc_ru: "Двери, разделяющие Т-мид. Первая преграда при пуше мида.",
    desc_es: "Puertas que dividen T Mid. Primera barrera al pushear Mid." },
  { id: "mid",         en: "Mid",            ru: "Мид",          es: "Mid",           poly: "260,260 380,260 380,440 260,440",
    desc_en: "Central open area. Winning Mid opens double-doors to B or splits A.",
    desc_ru: "Центральная открытая зона. Контроль мида открывает двери на Б или сплит на А.",
    desc_es: "Zona central abierta. Ganar Mid abre doble-puerta al B o split al A." },
  { id: "xbox",        en: "Xbox",           ru: "Икс-бокс",     es: "Xbox",          poly: "320,220 380,220 380,280 320,280",
    desc_en: "The iconic Xbox-sized crate in Mid. Jump spot, peek spot, bait spot.",
    desc_ru: "Культовый ящик в миде размером с Xbox. Прыжок, пик, бейт.",
    desc_es: "La caja tamaño Xbox en Mid. Salto, peek y bait." },
  { id: "lower_mid",   en: "Lower Tunnels",  ru: "Нижний мид",   es: "Túneles bajos", poly: "180,460 300,460 300,560 180,560",
    desc_en: "The tunnels from T side leading into B. Smoke-heavy execute route.",
    desc_ru: "Туннели с Т-стороны на Б. Путь исполнения, где много смоуков.",
    desc_es: "Túneles del lado T hacia B. Ruta de execute con muchos humos." },
  { id: "upper_tuns",  en: "Upper Tunnels",  ru: "Верхний тун",  es: "Túneles altos", poly: "40,440 180,440 180,540 40,540",
    desc_en: "Upper level of B Tunnels. First T contact with CT on B-push.",
    desc_ru: "Верх Б-туннелей. Первый контакт Т со СТ при пуше на Б.",
    desc_es: "Piso alto de los túneles B. Primer contacto T-CT en el push B." },
  { id: "b_site",      en: "B Site",         ru: "Б-плент",      es: "Sitio B",       poly: "40,580 300,580 300,780 40,780",
    desc_en: "Bombsite B. Two entries: Tunnels (T) and Mid Doors (CT rotate).",
    desc_ru: "Б-плент. Два входа: Туннели (Т) и мид-двери (СТ ротирует).",
    desc_es: "Sitio B. Dos entradas: Túneles (T) y Mid Doors (rotación CT)." },
  { id: "car_b",       en: "Car",            ru: "Машина",       es: "Auto",          poly: "60,620 160,620 160,700 60,700",
    desc_en: "The car on B. Classic plant behind it — safe from Mid door peek.",
    desc_ru: "Машина на Б. Классика — ставить за ней, безопасно от мид-двери.",
    desc_es: "Auto en B. Plant clásico detrás — seguro del peek de mid door." },
  { id: "back_plat",   en: "Back Plat",      ru: "Бэк-плат",     es: "Back Plat",     poly: "180,620 280,620 280,720 180,720",
    desc_en: "Back platform on B near CT tunnels. Anchor position.",
    desc_ru: "Задняя платформа на Б у СТ-туннелей. Позиция якоря.",
    desc_es: "Plataforma trasera en B cerca de CT tunnels. Posición anchor." },
  { id: "b_doors",     en: "B Doors",        ru: "Б-двери",      es: "Puertas B",     poly: "160,460 260,460 260,540 160,540",
    desc_en: "Doors between Mid and B. CT rotates through here after Mid loss.",
    desc_ru: "Двери между мидом и Б. СТ ротирует сюда при проигрыше мида.",
    desc_es: "Puertas entre Mid y B. CT rota por acá tras perder Mid." },
  { id: "ct_spawn",    en: "CT Spawn",       ru: "СТ-спавн",     es: "Spawn CT",      poly: "620,560 760,560 760,760 620,760",
    desc_en: "Counter-Terrorist starting position. 9 seconds to A, 10 to B.",
    desc_ru: "Спавн СТ. 9 секунд до А, 10 до Б.",
    desc_es: "Spawn CT. 9 seg al A, 10 al B." },
  { id: "palm",        en: "Palm",           ru: "Пальма",       es: "Palmera",       poly: "440,460 520,460 520,540 440,540",
    desc_en: "Palm tree near A Site. Off-angle hiding spot for CTs.",
    desc_ru: "Пальма у А-плента. Off-angle для СТ.",
    desc_es: "Palmera cerca del A. Posición off-angle para CTs." },
  { id: "suicide",     en: "Suicide",        ru: "Суицид",       es: "Suicide",       poly: "340,60 400,60 400,140 340,140",
    desc_en: "Short angle between T Spawn and Mid. Risky cross T must survive.",
    desc_ru: "Короткий угол между Т-спавном и мидом. Рискованный кросс Т.",
    desc_es: "Ángulo corto entre T Spawn y Mid. Cruce T riesgoso." },
];
