import type { Callout } from "./callouts-mirage";

// Overpass — urban Dutch map, 2013.
// A Site sunken below, B Site up top with the infamous bathrooms.
export const OVERPASS_CALLOUTS: Callout[] = [
  { id: "t_spawn",     en: "T Spawn",         ru: "Т-спавн",      es: "T Spawn",        poly: "40,40 220,40 220,160 40,160",
    desc_en: "Terrorist start. Long route to A, short to B via Connector.",
    desc_ru: "Т-спавн. Длинный путь на А, короткий на Б через коннектор.",
    desc_es: "Spawn T. Ruta larga al A, corta al B por Connector." },
  { id: "long",        en: "Long A",          ru: "Лонг",         es: "Long A",         poly: "240,40 500,40 500,140 240,140",
    desc_en: "The notorious Long A. AWP kingdom — control it or lose it.",
    desc_ru: "Легендарный Лонг А. Царство AWP — контролируй или теряй.",
    desc_es: "El famoso Long A. Reino del AWP — lo controlás o lo perdés." },
  { id: "long_water",  en: "Long Water",      ru: "Лонг-вода",    es: "Long Water",     poly: "520,40 680,40 680,140 520,140",
    desc_en: "Water pool halfway down Long. Splash = your position revealed.",
    desc_ru: "Лужа воды посреди Лонга. Плеск = ты спалился.",
    desc_es: "Charco de agua mitad de Long. Salpicadura = te descubriste." },
  { id: "a_site",      en: "A Site",          ru: "А-плент",      es: "Sitio A",        poly: "520,160 760,160 760,320 520,320",
    desc_en: "Lower bombsite A. Toxic, Alley, Pillar — three angles on entries.",
    desc_ru: "Нижний А-плент. Токсик, Аллея, Колонна — три угла для захода.",
    desc_es: "Sitio A inferior. Toxic, Alley, Pillar — tres ángulos de entrada." },
  { id: "pillar",      en: "Pillar",          ru: "Колонна",      es: "Pilar",          poly: "560,200 620,200 620,280 560,280",
    desc_en: "The concrete pillar on A. Default plant hides behind it.",
    desc_ru: "Бетонная колонна на А. За ней — дефолтная постановка.",
    desc_es: "Pilar de concreto en A. Detrás va el plant default." },
  { id: "toxic",       en: "Toxic",           ru: "Токсик",       es: "Toxic",          poly: "700,160 760,160 760,240 700,240",
    desc_en: "Corner near CT spawn. Named 'Toxic' because anchors camp here forever.",
    desc_ru: "Угол у СТ-спавна. Назвали 'Токсик', потому что якори тут живут вечно.",
    desc_es: "Rincón cerca del spawn CT. Se llama 'Toxic' porque los anchors campean eterno." },
  { id: "short_a",     en: "Short A",         ru: "Шорт А",       es: "Short A",        poly: "400,160 500,160 500,280 400,280",
    desc_en: "Alternate entry to A through Playground. Flanks Long defenders.",
    desc_ru: "Альтернативный заход на А через Плейграунд. Фланг на Лонг-защитников.",
    desc_es: "Entrada alternativa al A por Playground. Flanquea a los defensores de Long." },
  { id: "playground",  en: "Playground",      ru: "Плейграунд",   es: "Playground",     poly: "240,160 400,160 400,300 240,300",
    desc_en: "The kids' playground T uses to split A. Smoke Fountain and push.",
    desc_ru: "Детская площадка, которой Т сплитует А. Смоукают Фонтан — и идут.",
    desc_es: "El parque infantil que T usa para split A. Humean Fountain y pushean." },
  { id: "fountain",    en: "Fountain",        ru: "Фонтан",       es: "Fuente",         poly: "320,280 400,280 400,360 320,360",
    desc_en: "Central fountain between Playground and Short A. Key smoke.",
    desc_ru: "Центральный фонтан между Плейграундом и Шорт-А. Ключевой смоук.",
    desc_es: "Fuente central entre Playground y Short A. Humo clave." },
  { id: "monster",     en: "Monster",         ru: "Монстр",       es: "Monstruo",       poly: "240,320 320,320 320,420 240,420",
    desc_en: "Playground climbable structure. Hidden CT anchor spot.",
    desc_ru: "Лазилка на площадке. Скрытый СТ-якорь.",
    desc_es: "Estructura escalable del parque. Anchor CT oculto." },
  { id: "connector",   en: "Connector",       ru: "Коннектор",    es: "Conector",       poly: "40,180 220,180 220,340 40,340",
    desc_en: "T-side connector toward B. Fastest B-rush lane.",
    desc_ru: "Т-коннектор к Б. Самый быстрый Б-раш.",
    desc_es: "Conector T hacia B. Ruta de B-rush más rápida." },
  { id: "b_short",     en: "B Short",         ru: "Б-шорт",       es: "Short B",        poly: "40,360 200,360 200,440 40,440",
    desc_en: "Short path into B from T. Leads to Bank and Bananas.",
    desc_ru: "Короткий путь на Б от Т. Ведёт к Банку и Бананам.",
    desc_es: "Ruta corta al B desde T. Lleva a Bank y Bananas." },
  { id: "bananas",     en: "Bananas",         ru: "Бананы",       es: "Bananas",        poly: "60,460 180,460 180,540 60,540",
    desc_en: "Banana crates at B entry. Smoke cover during B execute.",
    desc_ru: "Ящики бананов у входа Б. Прикрытие смоуком при Б-заходе.",
    desc_es: "Cajas de bananas en entrada B. Cobertura de humo en execute B." },
  { id: "b_site",      en: "B Site",          ru: "Б-плент",      es: "Sitio B",        poly: "40,560 360,560 360,760 40,760",
    desc_en: "Upper bombsite. Small, narrow, covered. Bathrooms watch from above.",
    desc_ru: "Верхний плент. Маленький, узкий, закрытый. Туалеты смотрят сверху.",
    desc_es: "Sitio superior. Chico, angosto, cubierto. Los Baños miran desde arriba." },
  { id: "bank",        en: "Bank",            ru: "Банк",         es: "Bank",           poly: "60,580 160,580 160,660 60,660",
    desc_en: "Plant spot behind the raised bank on B. Protected from Heaven.",
    desc_ru: "Постановка за приподнятым банком на Б. Защищено от Хэвена.",
    desc_es: "Plant detrás del banco elevado en B. Protegido de Heaven." },
  { id: "car_b",       en: "Car",             ru: "Машина",       es: "Auto",           poly: "180,580 280,580 280,660 180,660",
    desc_en: "Car on B — alternate plant. Watch for Heaven peek.",
    desc_ru: "Машина на Б — альтернативная постановка. Следи за пиком с Хэвена.",
    desc_es: "Auto en B — plant alternativo. Ojo con el peek de Heaven." },
  { id: "bathrooms",   en: "Bathrooms",       ru: "Туалеты",      es: "Baños",          poly: "200,760 360,760 360,780 200,780",
    desc_en: "The infamous bathrooms. Olofboost happened above these.",
    desc_ru: "Легендарные туалеты. Над ними произошёл olofboost.",
    desc_es: "Los famosos baños. Arriba de estos pasó el olofboost." },
  { id: "heaven_b",    en: "Heaven",          ru: "Хэвен",        es: "Heaven",         poly: "260,460 400,460 400,560 260,560",
    desc_en: "The elevated CT overlook of B. Best anchor position on the map.",
    desc_ru: "Приподнятая СТ-позиция над Б. Лучший якорь на карте.",
    desc_es: "Posición CT elevada sobre B. El mejor anchor del mapa." },
  { id: "squeaky",     en: "Squeaky",         ru: "Скрипучка",    es: "Squeaky",        poly: "400,600 500,600 500,700 400,700",
    desc_en: "Squeaky door between B and the rest of the map. Always loud.",
    desc_ru: "Скрипучая дверь между Б и остальной картой. Всегда громкая.",
    desc_es: "Puerta chirriante entre B y el resto del mapa. Siempre ruidosa." },
  { id: "ct_stairs",   en: "CT Stairs",       ru: "СТ-лестница",  es: "Escalera CT",    poly: "540,440 660,440 660,560 540,560",
    desc_en: "CT stairs connecting A and B levels. Rotation spine.",
    desc_ru: "СТ-лестница между уровнями А и Б. Позвоночник ротаций.",
    desc_es: "Escalera CT conectando niveles A y B. Columna de rotación." },
  { id: "ct_spawn",    en: "CT Spawn",        ru: "СТ-спавн",     es: "Spawn CT",       poly: "680,560 760,560 760,760 680,760",
    desc_en: "Counter-Terrorist start. 8 seconds to A, 10 to B.",
    desc_ru: "Спавн СТ. 8 секунд до А, 10 до Б.",
    desc_es: "Spawn CT. 8 seg al A, 10 al B." },
  { id: "party",       en: "Party",           ru: "Парти",        es: "Party",          poly: "520,340 680,340 680,420 520,420",
    desc_en: "CT-side room between A and Long. Rotating defender passes through.",
    desc_ru: "СТ-комната между А и Лонгом. Через неё ходит ротирующий защитник.",
    desc_es: "Sala CT entre A y Long. Pasa el defensor rotando." },
];
