import type { Callout } from "./callouts-mirage";

// Ancient — jungle temple, 2021.
// Central donut, temple A, cave B, lots of angles.
export const ANCIENT_CALLOUTS: Callout[] = [
  { id: "t_spawn",    en: "T Spawn",        ru: "Т-спавн",     es: "T Spawn",       poly: "40,40 200,40 200,160 40,160",
    desc_en: "Terrorist start. Paths: Main to A via Temple, Mid via Ramp, B via Cave.",
    desc_ru: "Т-спавн. Пути: главный на А через Храм, мид через рампу, на Б через пещеру.",
    desc_es: "Spawn T. Rutas: Main al A por Temple, Mid por Ramp, B por Cave." },
  { id: "main",       en: "Main",           ru: "Мэйн",        es: "Main",          poly: "220,40 440,40 440,140 220,140",
    desc_en: "T Main path to A. Smoke-heavy execute lane.",
    desc_ru: "Т-мэйн на А. Смоук-тяжёлый исполняющий коридор.",
    desc_es: "Main T al A. Ruta de execute con muchos humos." },
  { id: "temple",     en: "Temple",         ru: "Храм",        es: "Templo",        poly: "460,40 620,40 620,180 460,180",
    desc_en: "Stone temple leading into A. Classic T-side pre-aim spot.",
    desc_ru: "Каменный храм ведёт на А. Классика для Т-преаима.",
    desc_es: "Templo de piedra hacia A. Clásico para pre-aim T." },
  { id: "a_site",     en: "A Site",         ru: "А-плент",     es: "Sitio A",       poly: "640,40 760,40 760,280 640,280",
    desc_en: "Bombsite A. Entries from Temple, Main, and Donut.",
    desc_ru: "А-плент. Заходы из Храма, Мэйна и Донута.",
    desc_es: "Sitio A. Entradas desde Templo, Main y Donut." },
  { id: "elbow",      en: "Elbow",          ru: "Локоть",      es: "Codo",          poly: "580,180 660,180 660,240 580,240",
    desc_en: "Tight corner into A from Temple side. Wide-swing death zone.",
    desc_ru: "Тесный угол на А со стороны Храма. Зона смерти для wide-swing.",
    desc_es: "Rincón estrecho al A por el lado del Templo. Zona mortal para wide-swing." },
  { id: "ct_a",       en: "CT Heaven",      ru: "СТ-хэвен",    es: "CT Heaven",     poly: "680,60 760,60 760,180 680,180",
    desc_en: "High CT overlook on A. AWP country.",
    desc_ru: "Верхняя СТ-позиция над А. Страна AWP.",
    desc_es: "Overlook alto CT sobre A. Territorio de AWP." },
  { id: "donut",      en: "Donut",          ru: "Донут",       es: "Donut",         poly: "460,200 580,200 580,340 460,340",
    desc_en: "The ring-shaped structure near A. Clear-this-first nightmare.",
    desc_ru: "Кольцевая конструкция у А. Кошмар для зачистки.",
    desc_es: "Estructura anular cerca del A. Pesadilla para limpiar." },
  { id: "ramp",       en: "T Ramp",         ru: "Т-рамп",      es: "Ramp T",        poly: "220,160 400,160 400,240 220,240",
    desc_en: "Ramp from T side leading to Mid. Control this early.",
    desc_ru: "Рампа с Т-стороны в мид. Контроль с первых секунд.",
    desc_es: "Rampa desde T hacia Mid. Controlalo temprano." },
  { id: "mid",        en: "Mid",            ru: "Мид",         es: "Mid",           poly: "260,260 440,260 440,460 260,460",
    desc_en: "Central open area with stone ruins. Mid winners split sites.",
    desc_ru: "Центральная открытая зона с руинами. Победа в миде — сплит на обе.",
    desc_es: "Zona central abierta con ruinas. Ganar Mid abre split a ambos sitios." },
  { id: "pillars",    en: "Pillars",        ru: "Пилоны",      es: "Pilares",       poly: "320,320 400,320 400,400 320,400",
    desc_en: "Stone pillars in Mid. Cover for slow pushes and lurkers.",
    desc_ru: "Каменные пилоны в миде. Прикрытие для медленных пушей и лёркеров.",
    desc_es: "Pilares de piedra en Mid. Cobertura para pushes lentos y lurkers." },
  { id: "tree",       en: "Tree",           ru: "Дерево",      es: "Árbol",         poly: "420,340 480,340 480,420 420,420",
    desc_en: "Big tree mid — jumping through leaves is free sound info.",
    desc_ru: "Большое дерево в миде — прыжки через листья = инфа по звуку.",
    desc_es: "Árbol grande en Mid — saltar entre hojas = info gratis por sonido." },
  { id: "cave",       en: "Cave",           ru: "Пещера",      es: "Cueva",         poly: "40,440 220,440 220,580 40,580",
    desc_en: "T entry to B through the cave. Cold, dark, stacked angles.",
    desc_ru: "Т-заход на Б через пещеру. Холодно, тёмно, много углов.",
    desc_es: "Entrada T al B por la cueva. Fría, oscura, muchos ángulos." },
  { id: "b_site",     en: "B Site",         ru: "Б-плент",     es: "Sitio B",       poly: "40,600 300,600 300,780 40,780",
    desc_en: "Bombsite B. Covered under jungle canopy. Tight execute angles.",
    desc_ru: "Б-плент. Покрытый джунглями. Тесные углы исполнения.",
    desc_es: "Sitio B. Cubierto por el dosel de la jungla. Ángulos de execute ajustados." },
  { id: "plant_b",    en: "Default B",      ru: "Дефолт Б",    es: "Default B",     poly: "80,640 200,640 200,720 80,720",
    desc_en: "Standard plant spot on B. Crates for cover.",
    desc_ru: "Стандартная постановка на Б. Ящики для прикрытия.",
    desc_es: "Plant estándar en B. Cajas de cobertura." },
  { id: "water_b",    en: "Water",          ru: "Вода",        es: "Agua",          poly: "220,640 300,640 300,720 220,720",
    desc_en: "Water puddle on B. Splash reveals crossers.",
    desc_ru: "Лужа на Б. Плеск выдаёт тех, кто пересекает.",
    desc_es: "Charco en B. Salpicadura delata a los que cruzan." },
  { id: "b_main",     en: "B Main",         ru: "Б-мэйн",      es: "B Main",        poly: "320,600 460,600 460,720 320,720",
    desc_en: "CT-side main entrance to B. Rotation path from Mid.",
    desc_ru: "СТ-мэйн вход на Б. Путь ротации из мида.",
    desc_es: "Entrada principal CT al B. Ruta de rotación desde Mid." },
  { id: "heaven_b",   en: "B Heaven",       ru: "Б-хэвен",     es: "B Heaven",      poly: "320,740 460,740 460,780 320,780",
    desc_en: "Elevated CT angle onto B. Pre-aim from here post-execute.",
    desc_ru: "Приподнятый СТ-угол на Б. Преаим отсюда после захода.",
    desc_es: "Ángulo CT elevado sobre B. Pre-aim desde acá post-execute." },
  { id: "ct_spawn",   en: "CT Spawn",       ru: "СТ-спавн",    es: "Spawn CT",      poly: "620,560 760,560 760,760 620,760",
    desc_en: "CT start. 9 seconds to A, 11 to B.",
    desc_ru: "СТ-спавн. 9 секунд до А, 11 до Б.",
    desc_es: "Spawn CT. 9 seg al A, 11 al B." },
  { id: "stairs",     en: "CT Stairs",      ru: "СТ-лестница", es: "Escalera CT",   poly: "500,460 620,460 620,560 500,560",
    desc_en: "Stairs connecting A side to B via CT spawn. Rotation highway.",
    desc_ru: "Лестница между А и Б через СТ-спавн. Шоссе ротаций.",
    desc_es: "Escalera entre A y B por spawn CT. Autopista de rotación." },
  { id: "ct_mid",     en: "CT Mid",         ru: "СТ-мид",      es: "CT Mid",        poly: "460,280 580,280 580,440 460,440",
    desc_en: "CT side of Mid. The AWP duel zone.",
    desc_ru: "СТ-сторона мида. Зона AWP-дуэлей.",
    desc_es: "Lado CT de Mid. Zona de duelo de AWP." },
  { id: "tunnels",    en: "Tunnels",        ru: "Туннели",     es: "Túneles",       poly: "240,480 340,480 340,580 240,580",
    desc_en: "Underground connector between Mid and B. Flank territory.",
    desc_ru: "Подземный коннектор между мидом и Б. Территория флангов.",
    desc_es: "Conector subterráneo entre Mid y B. Territorio de flanqueo." },
];
