export type Tactic = {
  id: string;
  map: string;
  side: "t" | "ct";
  name: string;
  shortName: string;
  difficulty: 1 | 2 | 3; // 1=easy, 2=med, 3=hard
  utility: string[]; // list of util needed
  steps: string[];
  why: string;
  counterBy: string; // how CT can counter (for T) or how T can counter (for CT)
  proExample?: string;
};

export const TACTICS: Tactic[] = [
  // ═══ MIRAGE ═══
  {
    id: "mir_t_a_4_1",
    map: "mirage",
    side: "t",
    name: "A Execute · 4-1 Split",
    shortName: "4-1 A Split",
    difficulty: 2,
    utility: ["2 smokes (CT, Stairs)", "2 flashes (Palace, Ramp)", "1 molly (Jungle)"],
    steps: [
      "One player takes Stairs control via Mid doors (the '1')",
      "The '4' stack Palace + Ramp with full utility",
      "Smoke CT, Stairs close simultaneously",
      "Flash over Palace, entry through site",
      "Lurker on Stairs holds rotate",
    ],
    why: "Spreads CT attention across two sites. Stairs pressure forces a defender there, opening Palace entry.",
    counterBy: "CT smokes Mid and stacks 3 on A early.",
    proExample: "Classic NAVI / G2 — standard since 2019",
  },
  {
    id: "mir_t_b_rush",
    map: "mirage",
    side: "t",
    name: "Fast B Apps Rush",
    shortName: "B Rush",
    difficulty: 1,
    utility: ["2 smokes (Kitchen, Market)", "1 flash (over Apps)", "1 molly (Van)"],
    steps: [
      "Full team runs B Apps from round start",
      "Lead smokes Kitchen, 2nd smokes Market",
      "Entry pops flash over Apps, swings first",
      "Molly default plant, plant for Ninja",
      "Post-plant from Van and Bench",
    ],
    why: "Exploits slow CT rotates. Beats any CT that over-commits to A/Mid control.",
    counterBy: "CT full-stacks B with utility thrown into Short.",
  },
  {
    id: "mir_ct_default",
    map: "mirage",
    side: "ct",
    name: "Default Setup",
    shortName: "Default CT",
    difficulty: 1,
    utility: ["1 smoke (Window)", "2 flashes (saved for Mid fight)"],
    steps: [
      "A anchor on Ticket + Triple (AWP)",
      "Mid AWPer plays Window, smokes Window R4+",
      "Connector support plays Short",
      "B anchor in Bench",
      "Rotator (IGL) plays CT near Jungle",
    ],
    why: "Standard CT balance — every site has info, Mid controlled by AWP, fast rotations via CT cross.",
    counterBy: "T-side should pressure Mid with smokes to disable Window AWP.",
  },

  // ═══ INFERNO ═══
  {
    id: "inf_t_banana",
    map: "inferno",
    side: "t",
    name: "Banana Smoke Execute",
    shortName: "Banana Smoke",
    difficulty: 2,
    utility: ["1 smoke (Coffin)", "1 smoke (New Box)", "2 mollies (Car, Sand)", "1 flash (pop over Logs)"],
    steps: [
      "2 players take early Car control",
      "Molly Logs + Sandbags to clear close angles",
      "Smoke Coffin + New Box when committing",
      "Pop-flash over Logs for entry",
      "Entry fragger swings site, trade 2m behind",
    ],
    why: "Banana is Inferno's bomb — whoever wins it controls the game. Utility-heavy executes beat stacked defenders.",
    counterBy: "CT early aggression on Car + Logs smoke from CT side.",
    proExample: "Natus Vincere vs FaZe · Major finals 2021",
  },
  {
    id: "inf_t_a_split",
    map: "inferno",
    side: "t",
    name: "A Apartments + Arch Split",
    shortName: "A 3-2 Split",
    difficulty: 3,
    utility: ["2 smokes (CT, Library)", "2 flashes", "2 mollies (Pit, Balcony)"],
    steps: [
      "3 go Apps, 2 take Mid to Arch",
      "Arch players smoke CT and Library",
      "Mollies into Pit and Balcony",
      "Apps pops Balcony flash",
      "Simultaneous entry — Apps drops, Arch crosses",
    ],
    why: "Two entry angles destroy CT cross-fires. Hard to execute — timing must be clean.",
    counterBy: "CT smokes Mid early and holds Arch aggressively.",
  },
  {
    id: "inf_ct_banana_aggro",
    map: "inferno",
    side: "ct",
    name: "Banana Aggression",
    shortName: "CT Banana Push",
    difficulty: 2,
    utility: ["1 smoke (Car)", "2 flashes (pop over Logs)", "1 molly (Bathroom clear)"],
    steps: [
      "First CT pushes Logs with teammate flash",
      "Molly bathroom to deny boost",
      "Smoke Car to deny Molotov",
      "Sit in Top Banana with AWP",
      "Fall back on grenade info",
    ],
    why: "Forces slow T-side start. Picks a kill or wastes 20 seconds of the round clock.",
    counterBy: "T-side full utility early — T-flash into CT push.",
  },

  // ═══ DUST 2 ═══
  {
    id: "d2_t_mid_b",
    map: "dust2",
    side: "t",
    name: "Mid → B Split",
    shortName: "Mid to B",
    difficulty: 2,
    utility: ["2 smokes (Xbox + Double)", "2 flashes (Tunnels, B doors)", "1 molly (Ninja corner)"],
    steps: [
      "2 players fight Mid, smoke Xbox",
      "Win Mid → smoke Double Doors for wrap",
      "3 players come from Tunnels",
      "Sync entry: Mid flashes B doors, Tunnels commits",
      "Plant safe behind Car, hold Back Plat + Tunnels",
    ],
    why: "Mid win cuts CT rotations in half. B split with 5 beats almost any B stack.",
    counterBy: "CT plays B-doors aggressive + Mid AWP with flash support.",
  },
  {
    id: "d2_t_long_take",
    map: "dust2",
    side: "t",
    name: "Long A Smoke Execute",
    shortName: "Long Smoke",
    difficulty: 1,
    utility: ["1 smoke (Cross)", "1 smoke (CT)", "1 molly (Default)", "2 flashes"],
    steps: [
      "Smoke CT Cross and CT mid-round",
      "Molotov Default to clear Goose",
      "Pop-flash over Long Doors",
      "Entry swings Pit",
      "Trade through Long, plant Default or Short",
    ],
    why: "Classic fundamental T-side execute. Works from Silver to Global.",
    counterBy: "CT takes early Pit/Long Doors control with mid-support.",
  },
  {
    id: "d2_ct_default",
    map: "dust2",
    side: "ct",
    name: "1-2-2 Default",
    shortName: "1-2-2 Setup",
    difficulty: 1,
    utility: ["1 molly (Xbox)", "1 smoke (Upper Tunnels)"],
    steps: [
      "1 AWPer Long (Pit)",
      "2 mid (Xbox or Car with smoke)",
      "2 B (one Back Plat, one Upper Tunnels molly)",
      "Mid rotates based on info",
      "A back-up via CT, B back-up via Mid Doors",
    ],
    why: "Balanced default. Every site has info, fast rotates via CT/Mid. Standard since 2013.",
    counterBy: "T-side Mid control neutralizes the rotations.",
  },

  // ═══ NUKE ═══
  {
    id: "nuke_t_outside_a",
    map: "nuke",
    side: "t",
    name: "Outside → A Execute",
    shortName: "Outside A",
    difficulty: 3,
    utility: ["2 smokes (Heaven, Hut)", "2 flashes (Silo, Garage)", "2 mollies (Rafters, site)"],
    steps: [
      "Take Outside control with Silo + Garage positions",
      "Smoke Heaven + Hut (or Squeaky)",
      "Molly Rafters and default",
      "Through Squeaky door — listen up for counter-utility",
      "Entry flash + commit, support trade",
    ],
    why: "Bypasses Main choke entirely. Astralis defined this strat 2018-2019.",
    counterBy: "CT early Silo/Outside push round 1 before T spreads.",
    proExample: "Astralis' whole identity was this plus Ramp stomp",
  },
  {
    id: "nuke_t_ramp_push",
    map: "nuke",
    side: "t",
    name: "Ramp Stomp → B",
    shortName: "Ramp to B",
    difficulty: 2,
    utility: ["1 smoke (Big Door)", "1 molly (Ramp)", "2 flashes"],
    steps: [
      "Full rush Ramp with molly to clear",
      "Smoke Big Door off Main rotation",
      "Drop to B as group",
      "Molly Control Room corner",
      "Plant Default, post-plant lock on Main",
    ],
    why: "Beats CTs with heavy A-side bias. Forces fast rotate from weakest position.",
    counterBy: "CT Ramp aggression with AWP + support.",
  },
  {
    id: "nuke_ct_outside_hold",
    map: "nuke",
    side: "ct",
    name: "Outside Early Aggression",
    shortName: "Outside Aggro",
    difficulty: 2,
    utility: ["1 smoke (T-Ramp)", "1 molly (Garage)", "2 flashes"],
    steps: [
      "CT AWPer pushes through Secret to Garage",
      "Teammate flashes over Silo",
      "Smoke T-Ramp to deny Outside control",
      "Pick off first T-player, fall back safely",
      "Set up default CT if no pick",
    ],
    why: "Denies Astralis-style Outside Execute. Forces T to go Main or Ramp.",
    counterBy: "T-side plays slow, clears Secret with utility first.",
  },

  // ═══ ANUBIS ═══
  {
    id: "anu_t_mid_control",
    map: "anubis",
    side: "t",
    name: "Mid Control Default",
    shortName: "Mid Default",
    difficulty: 2,
    utility: ["1 smoke (CT Mid)", "1 smoke (Bridge)", "2 flashes"],
    steps: [
      "2 players contest Mid early",
      "Smoke CT Mid to deny AWP",
      "Smoke Bridge to cross Water safely",
      "Once Mid taken, split via Connector A or B",
      "Late-round commit with 40+ sec on clock",
    ],
    why: "Anubis is a Mid-centric map. Owning Mid opens both sites with short walks.",
    counterBy: "CT AWPer plays Heaven or aggressive CT Mid.",
  },
  {
    id: "anu_t_b_canal",
    map: "anubis",
    side: "t",
    name: "Canal B Execute",
    shortName: "B Canal",
    difficulty: 2,
    utility: ["2 smokes (Pharmacy, Heaven)", "1 molly (Truck)", "2 flashes"],
    steps: [
      "3 players go Canal, 2 hold Mid",
      "Smoke Pharmacy and B Heaven",
      "Molly Truck / default plant spot",
      "Through water splash sound = information",
      "Pop-flash entry, plant Boxes, hold Heaven angle",
    ],
    why: "The water noise is a feature — CTs know you're coming but can't easily counter.",
    counterBy: "Fast CT rotate with flash over Canal entry.",
  },
  {
    id: "anu_ct_mid_awp",
    map: "anubis",
    side: "ct",
    name: "CT Mid AWP Setup",
    shortName: "Mid AWP",
    difficulty: 1,
    utility: ["1 smoke (Alley)", "1 flash (support)"],
    steps: [
      "AWPer holds CT Mid angle through bridge",
      "Support player flashes from Connector",
      "Back-up rotates between A Heaven and B",
      "If Mid contested — smoke Alley, fall to Connector",
    ],
    why: "Mid AWP dictates the round. Forces T to commit a site with no Mid info.",
    counterBy: "T flashes Bridge and forces AWP off angle.",
  },

  // ═══ OVERPASS ═══
  {
    id: "over_t_b_execute",
    map: "overpass",
    side: "t",
    name: "B Site Smoke Execute",
    shortName: "B Execute",
    difficulty: 2,
    utility: ["2 smokes (Heaven, Bathrooms)", "1 molly (Heaven)", "2 flashes (over Bananas)"],
    steps: [
      "Team takes Connector control",
      "Smoke Heaven + Bathrooms",
      "Molly Heaven platform",
      "Pop-flash over Bananas",
      "Plant Bank, post-plant from Car angle",
    ],
    why: "Bathrooms is the infamous boost angle — denying it closes the site. Heaven molly prevents the stall.",
    counterBy: "CT holds Heaven + rotates B-short aggressively.",
  },
  {
    id: "over_t_a_long",
    map: "overpass",
    side: "t",
    name: "Long A Control",
    shortName: "Long Take",
    difficulty: 3,
    utility: ["2 smokes (Truck, Fountain)", "2 flashes", "1 molly (Water pool)"],
    steps: [
      "Early Long presence with smokes",
      "Molly Water to deny splashing T-info",
      "Flash into Long from T Spawn side",
      "Use Playground as split entry",
      "Commit A with Fountain smoked off from Pillar",
    ],
    why: "Long is Overpass's marathon. Winning it opens two A angles.",
    counterBy: "CT Long AWP + connect rotate with molly.",
  },
  {
    id: "over_ct_b_stack",
    map: "overpass",
    side: "ct",
    name: "B Stack Anti-Rush",
    shortName: "B Stack",
    difficulty: 1,
    utility: ["1 smoke (Connector)", "1 molly (Bananas)", "1 flash (B-short)"],
    steps: [
      "3 CT stack Heaven + Bank + Bathrooms",
      "Molly Bananas R1/R2 to deny rush",
      "Smoke Connector late if push",
      "AWPer on Heaven, rifle on Bank",
      "Collapse if A call, rotate through CT Stairs",
    ],
    why: "B rushes are common round 2. A heavy B stack ends pistol force rounds fast.",
    counterBy: "T-side slow default, fake B, go A.",
  },

  // ═══ ANCIENT ═══
  {
    id: "anc_t_a_temple",
    map: "ancient",
    side: "t",
    name: "Temple → A Execute",
    shortName: "Temple A",
    difficulty: 2,
    utility: ["1 smoke (CT Heaven)", "1 smoke (Donut)", "1 molly (Elbow)", "2 flashes"],
    steps: [
      "Main push with utility support",
      "Smoke CT Heaven first",
      "Molly Elbow to clear the off-angle",
      "Smoke Donut to isolate site",
      "Entry through Temple, support trades",
    ],
    why: "Ancient A has many tight corners — utility clears them all so entry has fewer surprises.",
    counterBy: "CT stacks Donut, plays passive Heaven.",
  },
  {
    id: "anc_t_mid_rush",
    map: "ancient",
    side: "t",
    name: "Mid-to-B Split",
    shortName: "Mid B",
    difficulty: 2,
    utility: ["2 smokes (CT Mid, B Heaven)", "2 flashes", "1 molly (B Main)"],
    steps: [
      "Early Ramp control, smoke CT Mid",
      "3 players commit Cave, 2 hold Mid",
      "Molly B Main from Cave side",
      "Smoke B Heaven, flash entry",
      "Plant Default B, Mid players wrap Tunnels",
    ],
    why: "Tunnels wrap is key — it cuts off B Main rotations and secures post-plant.",
    counterBy: "CT Mid presence with AWP, Tunnels flash denies wrap.",
  },
  {
    id: "anc_ct_default",
    map: "ancient",
    side: "ct",
    name: "Balanced Default",
    shortName: "Default CT",
    difficulty: 1,
    utility: ["1 smoke (Ramp)", "1 molly (Cave)"],
    steps: [
      "1 A Heaven with AWP",
      "1 Donut",
      "1 CT Mid with rifle",
      "2 B (one B Heaven, one B Main molly)",
      "Smoke Ramp R2+ to delay Mid rush",
    ],
    why: "Ancient rewards passive CT play — the map has too many angles for aggressive hunts.",
    counterBy: "T-side full utility A execute or Mid force.",
  },
];

export const MAP_ORDER = ["mirage", "inferno", "dust2", "nuke", "anubis", "overpass", "ancient"] as const;
